// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiwchgaguztngcvagbcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpd2NoZ2FndXp0bmdjdmFnYmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDk5OTcsImV4cCI6MjA1MzIyNTk5N30.NIqMPklnBqkWIfYArqqr03YJkZZPhReSDnACc76kl5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);